export function createInitialState({ audioEnabledDefault, defaultFinanceAssets }) {
  return {
    gears: 0,
    purchaseMode: "1",
    lastTimestamp: performance.now(),
    accumulator: 0,
    pendingOfflineGears: 0,
    manualPower: 1,
    gpsMultiplier: 1,
    totalClicks: 0,
    lifetimeGears: 0,
    researchPoints: 0,
    lastRewardText: "",
    gameSpeed: 1,
    questIndex: 0,
    logs: [],
    autoBuy: false,
    autoBuyAccumulator: 0,
    activeOrder: null,
    audioEnabled: audioEnabledDefault,
    comboStreak: 0,
    comboTimer: 0,
    activeFloatingGains: 0,
    lastShakeAt: 0,
    lowPerfMode: false,
    lowPerfAudioSafe: false,
    categoryCollapse: { economy: false, goals: false },
    financeCapital: 0,
    financeTier: 0,
    financeLastInvestAt: 0,
    financeLastWithdrawAt: 0,
    financeStrategy: "balanced",
    financeHedgeUntil: 0,
    financeMetaPoints: 0,
    financeCreditBase: 0,
    financeStrategySwitches: 0,
    prestigeBranches: { legacy_manual: 0, legacy_line: 0 },
    debugPanelOpen: false,
    debugManualMult: 1,
    debugGpsMult: 1,
    financeSeasonIndex: 0,
    financeLeaderboard: [],
    financeAssets: { ...defaultFinanceAssets },
    financeLineage: 0,
    financeAutoPilot: false,
    financeAutoAccumulator: 0,
    overdriveUntil: 0,
    overdriveCooldownUntil: 0,
    overdriveActivations: 0
  };
}
